/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ComandosLeituraGravacao;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        
        int idade = leitor.nextInt();
                float cotacaoDolar = leitor.nextFloat();
                double cotacaoEuro - leitor.nextDouble();
                String nome = leitor.nextLine();
       
    }
}
