/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Principal;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      int idade = 10;
      float cotacaoDolar = 5.0f;
      double cotacaoEuro = 6.0d;
      char genero = 'M';
      byte pontos = 0;
      boolean estaCadastrador = false;
      
      String nome = "Esse é um texto de uma variavel String";
      
      +
              
      -
              
      /  
              
      *
              
      %        
    }
}
